# comment
cors.allowed_origins=*
cors.enable=true
resources.download.thread_pool_size=3
resources.upload.thread_pool_size=3
server.host=0.0.0.0
server.multipart.file_size_threshold=50MB
server.multipart.max_file_size=500MB
server.multipart.max_request_size=500MB
server.port=9090
